default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: Mz0PMCtH0OspYAlbqPwBW5zQHEv3eywD
  host: dpg-chgulvrhp8u065rbc15g-a.singapore-postgres.render.com

development:
  <<: *default
  database: kindle_4iew
# test:
#   <<: *default
#   database: myapp_test

# production:
#   <<: *default
#   database: myapp_production
#   username: <%= ENV["POSTGRES_USERNAME"] %>
#   password: <%= ENV["POSTGRES_PASSWORD"] %>
